name: CI Testing
on: push

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.local/bin
            ~/.local/lib
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Install stockfish
        run: |
          sudo apt-get -y install stockfish

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
        shell: bash

      - name: Test with pytest
        run: |
          pytest
        working-directory: backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
